//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Lab_8
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON
    {
        public int id_person { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
        public int age { get; set; }
        public string phone { get; set; }
        public int id_address { get; set; }
        public int id_passport { get; set; }
    
        public virtual ADDRESS ADDRESS { get; set; }
        public virtual PASSPORT PASSPORT { get; set; }
    }
}
