//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Lab_11
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class RECORD : INotifyPropertyChanged
    {
        [Key]
        public string FIO { get; set; }
        public string SUBJECT { get; set; }
        public DateTime DATE { get; set; }
        public TimeSpan TIME { get; set; }
        public bool FREE { get; set; }

        public bool Free
        {
            get => FREE;
            set
            {
                if (FREE != value)
                {
                    FREE = value;
                    OnPropertyChanged(nameof(Free));
                }
            }
        }

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void OnPropertyChanged(string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }
}
