//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Lab_10
{
    using Microsoft.EntityFrameworkCore.Metadata.Internal;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class PERSON
    {
        [Key]
        public int id_person { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
        public int age { get; set; }
        public string phone { get; set; }
        public int id_address { get; set; }
        public int id_passport { get; set; }

        [ForeignKey("id_address")]
        public virtual ADDRESS ADDRESS { get; set; }
        [ForeignKey("id_passport")]
        public virtual PASSPORT PASSPORT { get; set; }
    }
}
